---
title: "Lab 05 - Importing and Recoding `earthquakes`"
author: "Nyla Williams"
date: "3/12/2024"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse)
library(readxl)
library(openintro)
library(skimr)
library(janitor)
```

## Exercises

### Exercise 1

```{r}
skim(earthquakes)
```


### Exercise 2

```{r insepct}


earthquakes_1 <- read_csv("data/earthquakes-1.csv")
earthquakes_2 <- read_tsv("data/earthquakes-2.txt")
earthquakes_3 <- read_xlsx("data/earthquakes-3.xlsx")


```


### Exercise 3

```{r glimpse}

glimpse(earthquakes_1)
glimpse(earthquakes_2)
glimpse(earthquakes_3)

```

This code imports the earthquakes -3 xlsx file with the appropriate data types

### Exercise 4

```{r joining-earthquakes}

earthquakes_1 %>%
  full_join(earthquakes_2) %>% 
  full_join(earthquakes_3) %>% skim()

```


### Exercise 5

```{r earthquakes-badnames, eval = F}
earthquakes_badnames <- read_csv("data/earthquakes-badnames-na.csv") %>% 
  glimpse()
```




### Exercise 6

```{r fix-earthquakes-badnames-nas, eval = F}
read_csv("data/earthquakes-badnames-na.csv",
         na = c("NA", "."))
```


### Exercise 7

```{r fix-names, message = F, warning = F}
read_csv("data/earthquakes-badnames-na.csv",
         na = c("NA", ".")) %>%
         janitor::clean_names()
names(earthquakes_fixed_names)
```
The problem with the names are the spaces in between the words for the titles. 


### Exercise 8

```{r fix-richter, message = F, warning = F}

read_csv("data/earthquakes-badnames-na.csv",
         na = c("NA", ".")) %>% 
  janitor::clean_names() %>%
  mutate(richter = case_when(
    richter =="seven" ~ "7",
         TRUE ~ richter),
richter = as.numeric(richter))
```


### Exercise 9

```{r relevel-month, message = F, warning = F}


earthquakes_correct <- read_csv("data/earthquakes-badnames-na.csv", 
        na = c("NA", ".")) %>% janitor::clean_names() %>%
  mutate(richter = case_when(
    richter =="seven" ~ "7",
    TRUE ~ richter),
richter = as.numeric(richter),
month = fct_relevel(month, "January", "February", "March", "April", "May", "June", "July", 
                    "August", "September", "October", "November", "December"))

earthquakes_correct %>% count(month)
```


### Exercise 10

```{r write-read-rds, message = F, warning = F}

write_rds(earthquakes_correct, file = "data/earthquakes-correct.rds")

earthquakes_correct <- read_rds("data/earthquakes-correct.rds")

earthquakes_correct %>%
count(month)

```
